apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: {{ .Values.namespace }}-service
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.namespace }}-service
    tier: api-gateway 
spec:
  selector: 
    matchLabels: 
      app: {{ .Values.namespace }}-service
  template: 
    metadata: 
      name: {{ .Values.namespace }}-service
      labels: 
        app: {{ .Values.namespace }}-service
        tier: quote-service 
      annotations:
        jenkins/build: {{ (((.Values.metadata).jenkins).buildTag) | quote }}
        git/commitId: {{ (((.Values.metadata).git).commitId) | quote }}
    spec:
      containers: 
        - name: {{ .Values.namespace }}-service
          image: "{{ (((.Values.services).registry).uri) }}/paulappz/quote-service:{{ ((.Values.deployment).tag) }}"
          imagePullPolicy: Always
          envFrom:
          - secretRef:
                name: {{ .Values.namespace }}-secrets
          {{- if (((.Values.services).registry).secret) }}
          imagePullSecrets:
          - name: {{ .Values.services.registry.secret }}
          {{- end }}
          ports:
          - name: service-port
            containerPort: 9000