apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-api-gateway
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.namespace }}-api-gateway
  ports:
    - name: http
      port: 80
      targetPort: api-port
      protocol: TCP
    - name: https
      port: 443
      targetPort: api-port
    