apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: {{ .Values.namespace }}-web
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.namespace }}-web
    tier: frontend 
spec:
  selector: 
    matchLabels: 
      app: {{ .Values.namespace }}-web
  template: 
    metadata: 
      name: {{ .Values.namespace }}-web
      labels: 
        app: {{ .Values.namespace }}-web
        tier: frontend 
      annotations:
        jenkins/build: {{ (((.Values.metadata).jenkins).buildTag) | quote }}
        git/commitId: {{ (((.Values.metadata).git).commitId) | quote }}
    spec:
      containers: 
        - name: {{ .Values.namespace }}-web
          image: "{{ (((.Values.services).registry).uri) }}/paulappz/quote-web:{{ ((.Values.deployment).tag) }}"
          imagePullPolicy: Always
          {{- if (((.Values.services).registry).secret) }}
          imagePullSecrets:
          - name: {{ .Values.services.registry.secret }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ .Values.namespace }}-config-quote-web
          ports:
          - name: web-port
            containerPort: 80