apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-web
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.namespace }}-web
  ports:
  - name: http
    port: 80
    targetPort: web-port
    protocol: TCP
  - name: https
    port: 443
    targetPort: web-port
    