apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-quote-web
  namespace: {{ .Values.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    {{- if (((.Values.deployment).https).ssl) }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:{{ .Values.services.aws.region }}:{{ .Values.services.aws.account }}:certificate/{{ .Values.deployment.https.ssl }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    {{- end }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
  selector:
    app: {{ .Values.namespace }}-quote-web
  type: LoadBalancer